source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '13.4'

# Auto-linking for dependencies
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'
require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/react-native-unimodules/cocoapods'

target 'FriendlyFades' do
  use_react_native!
  use_unimodules!
  use_native_modules!

  # Specify Firebase pods with explicit versions
  pod 'Firebase/CoreOnly', '10.22.0'
  pod 'FirebaseAuth', '10.22.0'
  pod 'FirebaseFirestore', '10.22.0'
  pod 'FirebaseMessaging', '10.22.0'
  pod 'FirebaseStorage', '10.22.0'
  # Add other Firebase modules as needed

  post_install do |installer|
    react_native_post_install(installer)
    __apply_Xcode_12_5_M1_post_install_workarounds(installer)
  end
end
